### ISSUE TITLE
Compatibility with mtl-2.3

### ISSUE THREAD

**Issue by sjakobi** [frasertweedale/hs-jose#107]
```
Building library for jose-0.9..
[ 1 of 18] Compiling Crypto.JOSE.AESKW ( src/Crypto/JOSE/AESKW.hs, dist/build/Crypto/JOSE/AESKW.o, dist/build/Crypto/JOSE/AESKW.dyn_o )

src/Crypto/JOSE/AESKW.hs:76:29: error:
    Variable not in scope: join :: [[Int]] -> [b]
   |
76 |     let coords = zip [1..] (join (replicate 6 [1 .. n `div` 8]))
   |                             ^^^^
```

Note that some dependencies aren't compatible yet, e.g. https://github.com/haskell-tls/hs-certificate/issues/129.

**Comment by frasertweedale** [comment]
I'll wait until next release of mtl-2.3.x with the fix for https://github.com/haskell/mtl/issues/117, as well as for *hs-certificate* to unbreak (make the restoration of `ExceptT` export will suffice for that).  Then I should be able to properly address this.
