### ISSUE TITLE
Hackage release?

### ISSUE THREAD

**Issue by parsonsmatt** [frasertweedale/hs-jose#110]
I'm going through our dependencies and noticed that we're depending on a Git revision for this, due to the orphan `MonadRandom` instance

I see that this commit was landed in April '22. Is there any help necessary to get a Hackage release for this?

**Comment by frasertweedale** [comment]
There was a reason I held back from cutting a release.  But I no longer remember the reason.  So I'll just do it, in the next day or so.

**Comment by frasertweedale** [comment]
Released: https://hackage.haskell.org/package/jose-0.10

**Comment by parsonsmatt** [comment]
Thank you 🙌🏻
