### ISSUE TITLE
Custom JWTValidationSettings

### ISSUE THREAD

**Issue by whitehead1415** [frasertweedale/hs-jose#24]
In the example it shows verifying a jwt.

```
doJwtVerify :: [String] -> IO ()
doJwtVerify [jwkFilename, jwtFilename] = do
  Just jwk <- decode <$> L.readFile jwkFilename
  jwtData <- L.readFile jwtFilename
  result <- runExceptT (
    decodeCompact jwtData
    >>= validateJWSJWT defaultJWTValidationSettings jwk)
  case result of
    Left e -> print (e :: JWTError) >> exitFailure
    Right _ -> exitSuccess
```

How would one construct an alternative `JWTValidationSettings` than what `defaultJWTValidationSettings` gives you?

In particular I am trying to verify that the audience is correct.

**Comment by frasertweedale** [comment]
Hi.  You do:

```
let
  audPred :: StringOrURI -> Bool
  audPred = (`elem` ["valid", "audiences"])
  myValidationSettings = set audiencePredicate audPred defaultValidationSettings
```

Set whatever `audiencePredicate` you need.

I'll update the `example` program with a trivial example of doing this (probably
by optionally reading valid audience(s) from trailing CLI arg(s).
