### ISSUE TITLE
jose-0.3.38.0 can't compile its own test suite

### ISSUE THREAD

**Issue by peti** [frasertweedale/hs-jose#4]
Citing from http://hydra.cryp.to/build/606676/nixlog/1/raw:

    Preprocessing test suite 'tests' for jose-0.3.38.0...

    test/Test.hs:17:8:
        Could not find module ‘JWK’
        Use -v to see a list of the files searched for.

    test/Test.hs:18:8:
        Could not find module ‘JWS’
        Use -v to see a list of the files searched for.

    test/Test.hs:19:8:
        Could not find module ‘JWT’
        Use -v to see a list of the files searched for.

    test/Test.hs:20:8:
        Could not find module ‘Types’
        Perhaps you meant
          CTypes (needs flag -package haskell98-2.0.0.3)
          Type (needs flag -package ghc-7.8.4)
        Use -v to see a list of the files searched for.

**Comment by frasertweedale** [comment]
Thanks for reporting!  I was missing some modules in the distribution.

v0.3.41.0 should fix the issue: http://hackage.haskell.org/package/jose-0.3.41.0
