### ISSUE TITLE
JWT example in documentation incorrect

### ISSUE THREAD

**Issue by centromere** [frasertweedale/hs-jose#49]
In [the documentation](https://github.com/frasertweedale/hs-jose/blob/db1949a1ba99b4f92f9847d0d30b3c0e66b7dbdc/src/Crypto/JWT.hs#L43) the example reads:

```haskell
signClaims jwk (newJWSHeader (Protected, alg)) claims
```

however, the type of `signClaims` is:

```haskell
signClaims :: (MonadRandom m, MonadError e m, AsError e) => JWK -> JWSHeader () -> ClaimsSet -> m SignedJWT
```

In order for it to work the type would have to be:

```haskell
signClaims :: (MonadRandom m, MonadError e m, AsError e) => JWK -> JWSHeader Protection -> ClaimsSet -> m SignedJWT
```

or the example would need to be changed to:

```haskell
signClaims jwk (newJWSHeader ((), alg)) claims
```

**Comment by frasertweedale** [comment]
@centromere thanks for reporting!
