### ISSUE TITLE
broken with GHC-8.2

### ISSUE THREAD

**Issue by phadej** [frasertweedale/hs-jose#51]
See https://matrix.hackage.haskell.org/package/jose

Upper-boundless dependency on `template-haskell` is a bad idea. IIRC it breaks with each major version.

This is impediment for making `servant-auth` GHC-8.2 ready.

**Comment by phadej** [comment]
You can test GHC-8.2-rc3 with stack:
- https://www.reddit.com/r/haskell/comments/6lvles/announce_ghc_821_release_candidate_3_available/djwzcr4/
- https://gist.github.com/tfausak/623d283cfe7a338bcbfca56ddfec0ecd

**Comment by frasertweedale** [comment]
We already had the fix in master.  Have cherry-picked the fix to maint/0.6 and cut release v0.6.0.3.

Will add upper bound on template-haskell dep soon.

Thanks!

**Comment by phadej** [comment]
@frasertweedale could you make revisions for old jose releases, (the [matrix](https://matrix.hackage.haskell.org/package/jose) shows what's broken). I tripped on this, as solver happily picks 0.5.x versions (when packages have `jose <0.6` bound) when used with GHC-8.2

**Comment by frasertweedale** [comment]
On Mon, Jul 17, 2017 at 01:03:02PM +0000, Oleg Grenrus wrote:
> @frasertweedale could you make revisions for old jose releases,
> (the [matrix](https://matrix.hackage.haskell.org/package/jose)
> shows what's broken). I tripped on this, as solver happily picks
> 0.5.x versions (when packages have `jose <0.6` bound) when used
> with GHC-8.2
> 
Sure, will get onto this in next day or so.

Cheers,
Fraser

**Comment by frasertweedale** [comment]
@phadej http://hackage.haskell.org/package/jose-0.5.0.5 <- there ya go!
