### ISSUE TITLE
windows build failure due to example's unix dependency (version 0.8.0.0)

### ISSUE THREAD

**Issue by robx** [frasertweedale/hs-jose#83]
I see postgrest build failures on windows since the update to 0.8.0.0:

```
Error: While constructing the build plan, the following exceptions were
encountered:
In the dependencies for jose-0.8.0.0:
    unix needed, but the stack configuration has no specified version  (latest
         matching version is 2.7.2.2)
needed due to postgrest-6.0.0 -> jose-0.8.0.0
```

I see that that has been fixed in master by adding a flag -- would you consider making an 0.8.0.1-release on hackage that includes this?

**Comment by frasertweedale** [comment]
Ta-da! https://hackage.haskell.org/package/jose-0.8.1.0

Thanks for your patience.  Let me know if there are further issues.

**Comment by steve-chavez** [comment]
@frasertweedale Sorry, could you add a git tag for 8.1.0? We'd like to pin jose by tag instead of commit for a static build of postgrest using Nix.

**Comment by frasertweedale** [comment]
@steve-chavez done.
